#!/bin/bash

#Colors vars
green_color="\033[1;32m"
green_color_title="\033[0;32m"
red_color="\033[1;31m"
red_color_slim="\033[0;031m"
blue_color="\033[1;34m"
cyan_color="\033[1;36m"
brown_color="\033[0;33m"
yellow_color="\033[1;33m"
pink_color="\033[1;35m"
white_color="\e[1;97m"
normal_color="\e[1;0m"

function last_echo() {
        echo -e "${2}$*${normal_color}"
}

function echo_green() {
	last_echo "${1}" "${green_color}"
}

function echo_blue() {
	last_echo "${1}" "${blue_color}"
}

function echo_yellow() {
	last_echo "${1}" "${yellow_color}"
}

function echo_red() {
	last_echo "${1}" "${red_color}"
}

function echo_red_slim() {
	last_echo "${1}" "${red_color_slim}"
}

function echo_green_title() {
	last_echo "${1}" "${green_color_title}"
}

function echo_pink() {
	last_echo "${1}" "${pink_color}"
}

function echo_cyan() {
	last_echo "${1}" "${cyan_color}"
}

function echo_brown() {
	last_echo "${1}" "${brown_color}"
}

function echo_white() {
	last_echo "${1}" "${white_color}"
}

function git_manager() {
    read -p "upload/clone? u/c: " git_m
    echo_pink "$git_m"

    if [ "$git_m" = "u" ]; then
        git init
        git add .
        read -p "[+]  Masukan commit: " comit
        git commit -m "$comit"
        read -p "[+]  Masukan http: " http
        git remote add origin "$http"
        git push -f origin master

    elif [ "$git_m" = "c" ]; then
        read -p "[+]  Masukan link: " git_url
        pwd
        git clone "$git_url"
    else
        echo_red "[!]  input git salah"
    fi
}

function configure() {
    read -p "[+]  install web server y/n?" satu
    if [ "$satu" = "y" ]; then
        apt install php-apache
        echo
        read -p "[+] edit httpd.conf y/n?" dua
        if [ "$dua" = "y" ]; then
            cd "$PREFIX/etc/apache2/"
            ls;echo
            echo_green "Tambah ini:"
            echo_green "LoadModule php7_module /data/data/com.termux/file>"
            echo_green "<FilesMatch \.php$>"
            echo_green "    SetHandler application/x-httpd-php"
            echo_green "</FilesMatch>"
        fi
    fi

    read -p "[+]  install nano (editor text) y/n?" tiga
    if [ "$tiga" = "y" ]; then
        apt install nano
    fi

    read -p "[+]  install git (upload/download script) y/n?" empat
    if [ "$empat" = "y" ]; then
        apt install git
    fi

    read -p "[+]  install wget (download file) y/n?" lima
    if [ "$lima" = "y" ]; then
        apt install wget
    fi
}

echo
echo_green_title "Welcome AI termux"
echo_blue "[+]  configure"
echo_blue "[+]  git_manager"
echo
read -p "Masukan Aksi: " aksi

echo_pink "$aksi"
echo

if [ "$aksi" = "git_manager" ]; then
     git_manager
elif [ "$aksi" = "configure" ]; then
     configure
else
     echo_red "[!] input salah"
     echo
fi
echo
echo
